// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEtSKm8tKgSLyc7Xw4hobzd02oa30jYYc',
    appId: '1:305118314905:android:ff46c864d9892fcc525308',
    messagingSenderId: '305118314905',
    projectId: 'tiktok-ict',
    storageBucket: 'tiktok-ict.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-MBHW4O8vcziCAGBsC4CjYzOa_iwsjIs',
    appId: '1:305118314905:ios:d16c76eec1c5bb3c525308',
    messagingSenderId: '305118314905',
    projectId: 'tiktok-ict',
    storageBucket: 'tiktok-ict.appspot.com',
    androidClientId: '305118314905-359knfbjd4g6dnmrchuvldk8d9v4erct.apps.googleusercontent.com',
    iosClientId: '305118314905-ebadkar9ltu1bsljm9n1ncosuci9bqu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
