// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAynWZvr_SnIJusD-B3QKqeRE2v5yuSGUk',
    appId: '1:851549237006:android:289c27d9163f91a630715f',
    messagingSenderId: '851549237006',
    projectId: 'tiktokclone-1fc21',
    storageBucket: 'tiktokclone-1fc21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ9AaHJylagFmmYEA5DKNXfzYZfBxphfc',
    appId: '1:851549237006:ios:5ceb661fa6ba2e0530715f',
    messagingSenderId: '851549237006',
    projectId: 'tiktokclone-1fc21',
    storageBucket: 'tiktokclone-1fc21.appspot.com',
    androidClientId: '851549237006-jmgnsiv3dpe1s6lcsdujuun3fkommg4b.apps.googleusercontent.com',
    iosClientId: '851549237006-8nv4tf5jm0rh1pm32ien97degsjv5opf.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
